/********************************************************************
*
*
*    ClientGame: Decal Clip Helpers.
*
*
********************************************************************/
#pragma once

#include <cstdint>

#include "sharedgame/sg_decal_shared.h"

typedef struct mface_s mface_t;

/**
*    @brief  Clip context built from a decal spawn request.
**/
typedef struct clg_decal_clip_context_s {
    sg_decal_spawn_params_t spawn;
    vec3_t basisRight;
    vec3_t basisUp;
    vec3_t basisForward;
    float halfSize;
    float halfDepth;
} clg_decal_clip_context_t;

/**
*    @brief  Candidate world surface represented as a concrete receiver polygon source.
**/
typedef struct clg_world_surface_s {
    vec3_t origin;
    vec3_t normal;
    vec3_t tangent;
    vec3_t bitangent;
	//! True when the impact projects inside this concrete BSP face.
	bool containsImpactPoint;
	int32_t entityNumber;
	const mface_t *bspFace;
} clg_world_surface_t;

/**
*    @brief  Polygon generated by clipping one candidate surface.
**/
typedef struct clg_decal_clip_polygon_s {
    vec3_t positions[ 32 ];
    vec2_t uv[ 32 ];
    int32_t vertexCount;
} clg_decal_clip_polygon_t;

/**
*    @brief  Builds clip context from decal spawn payload.
*    @param  spawn Spawn payload describing projected decal volume.
*    @param  outContext [out] Built clipping context.
*    @return True when context is valid and usable.
**/
const bool CLG_DecalClip_BuildContext( const sg_decal_spawn_params_t &spawn, clg_decal_clip_context_t *outContext );

/**
*    @brief  Gathers candidate world surfaces from BSP faces intersecting the decal volume bounds.
*    @param  context Clipping context.
*    @param  outSurfaces [out] Destination array for gathered candidate surfaces.
*    @param  maxSurfaces Maximum surface entries writable in output array.
*    @return Number of candidate surfaces written.
**/
int32_t CLG_DecalClip_GatherCandidateSurfaces( const clg_decal_clip_context_t &context, clg_world_surface_t *outSurfaces, const int32_t maxSurfaces );

/**
*    @brief  Clips one candidate surface to decal footprint and returns a polygon.
*    @param  context Clipping context.
*    @param  surface Candidate surface to clip.
*    @param  outPolygon [out] Result polygon in world space with local UV mapping.
*    @return True if a non-empty polygon was produced.
**/
const bool CLG_DecalClip_ClipSurfaceToDecal( const clg_decal_clip_context_t &context, const clg_world_surface_t *surface, clg_decal_clip_polygon_t *outPolygon );
