/*
Copyright (C) 2022 Andrey Nazarov

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License along
with this program; if not, write to the Free Software Foundation, Inc.,
51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
*/

SDL_SCANCODE_A = (SDL_Scancode)'a',
SDL_SCANCODE_B = (SDL_Scancode)'b',
SDL_SCANCODE_C = (SDL_Scancode)'c',
SDL_SCANCODE_D = (SDL_Scancode)'d',
SDL_SCANCODE_E = (SDL_Scancode)'e',
SDL_SCANCODE_F = (SDL_Scancode)'f',
SDL_SCANCODE_G = (SDL_Scancode)'g',
SDL_SCANCODE_H = (SDL_Scancode)'h',
SDL_SCANCODE_I = (SDL_Scancode)'i',
SDL_SCANCODE_J = (SDL_Scancode)'j',
SDL_SCANCODE_K = (SDL_Scancode)'k',
SDL_SCANCODE_L = (SDL_Scancode)'l',
SDL_SCANCODE_M = (SDL_Scancode)'m',
SDL_SCANCODE_N = (SDL_Scancode)'n',
SDL_SCANCODE_O = (SDL_Scancode)'o',
SDL_SCANCODE_P = (SDL_Scancode)'p',
SDL_SCANCODE_Q = (SDL_Scancode)'q',
SDL_SCANCODE_R = (SDL_Scancode)'r',
SDL_SCANCODE_S = (SDL_Scancode)'s',
SDL_SCANCODE_T = (SDL_Scancode)'t',
SDL_SCANCODE_U = (SDL_Scancode)'u',
SDL_SCANCODE_V = (SDL_Scancode)'v',
SDL_SCANCODE_W = (SDL_Scancode)'w',
SDL_SCANCODE_X = (SDL_Scancode)'x',
SDL_SCANCODE_Y = (SDL_Scancode)'y',
SDL_SCANCODE_Z = (SDL_Scancode)'z',
SDL_SCANCODE_1 = (SDL_Scancode)'1',
SDL_SCANCODE_2 = (SDL_Scancode)'2',
SDL_SCANCODE_3 = (SDL_Scancode)'3',
SDL_SCANCODE_4 = (SDL_Scancode)'4',
SDL_SCANCODE_5 = (SDL_Scancode)'5',
SDL_SCANCODE_6 = (SDL_Scancode)'6',
SDL_SCANCODE_7 = (SDL_Scancode)'7',
SDL_SCANCODE_8 = (SDL_Scancode)'8',
SDL_SCANCODE_9 = (SDL_Scancode)'9',
SDL_SCANCODE_0 = (SDL_Scancode)'0',
SDL_SCANCODE_RETURN = (SDL_Scancode)K_ENTER,
SDL_SCANCODE_ESCAPE = (SDL_Scancode)K_ESCAPE,
SDL_SCANCODE_BACKSPACE = (SDL_Scancode)K_BACKSPACE,
SDL_SCANCODE_TAB = (SDL_Scancode)K_TAB,
SDL_SCANCODE_SPACE = (SDL_Scancode)K_SPACE,
SDL_SCANCODE_MINUS = (SDL_Scancode)'-',
SDL_SCANCODE_EQUALS = (SDL_Scancode)'=',
SDL_SCANCODE_LEFTBRACKET = (SDL_Scancode)'[',
SDL_SCANCODE_RIGHTBRACKET = (SDL_Scancode)']',
SDL_SCANCODE_BACKSLASH = (SDL_Scancode)'\\',
SDL_SCANCODE_SEMICOLON = (SDL_Scancode)';',
SDL_SCANCODE_APOSTROPHE = (SDL_Scancode)'\'',
SDL_SCANCODE_GRAVE = (SDL_Scancode)'`',
SDL_SCANCODE_COMMA = (SDL_Scancode)',',
SDL_SCANCODE_PERIOD = (SDL_Scancode)'.',
SDL_SCANCODE_SLASH = (SDL_Scancode)'/',
SDL_SCANCODE_CAPSLOCK = (SDL_Scancode)K_CAPSLOCK,
SDL_SCANCODE_F1 = (SDL_Scancode)K_F1,
SDL_SCANCODE_F2 = (SDL_Scancode)K_F2,
SDL_SCANCODE_F3 = (SDL_Scancode)K_F3,
SDL_SCANCODE_F4 = (SDL_Scancode)K_F4,
SDL_SCANCODE_F5 = (SDL_Scancode)K_F5,
SDL_SCANCODE_F6 = (SDL_Scancode)K_F6,
SDL_SCANCODE_F7 = (SDL_Scancode)K_F7,
SDL_SCANCODE_F8 = (SDL_Scancode)K_F8,
SDL_SCANCODE_F9 = (SDL_Scancode)K_F9,
SDL_SCANCODE_F10 = (SDL_Scancode)K_F10,
SDL_SCANCODE_F11 = (SDL_Scancode)K_F11,
SDL_SCANCODE_F12 = (SDL_Scancode)K_F12,
SDL_SCANCODE_PRINTSCREEN = (SDL_Scancode)K_PRINTSCREEN,
SDL_SCANCODE_SCROLLLOCK = (SDL_Scancode)K_SCROLLOCK,
SDL_SCANCODE_PAUSE = (SDL_Scancode)K_PAUSE,
SDL_SCANCODE_INSERT = (SDL_Scancode)K_INS,
SDL_SCANCODE_HOME = (SDL_Scancode)K_HOME,
SDL_SCANCODE_PAGEUP = (SDL_Scancode)K_PGUP,
SDL_SCANCODE_DELETE = (SDL_Scancode)K_DEL,
SDL_SCANCODE_END = (SDL_Scancode)K_END,
SDL_SCANCODE_PAGEDOWN = (SDL_Scancode)K_PGDN,
SDL_SCANCODE_RIGHT = (SDL_Scancode)K_RIGHTARROW,
SDL_SCANCODE_LEFT = (SDL_Scancode)K_LEFTARROW,
SDL_SCANCODE_DOWN = (SDL_Scancode)K_DOWNARROW,
SDL_SCANCODE_UP = (SDL_Scancode)K_UPARROW,
SDL_SCANCODE_NUMLOCKCLEAR = (SDL_Scancode)K_NUMLOCK,
SDL_SCANCODE_KP_DIVIDE = (SDL_Scancode)K_KP_SLASH,
SDL_SCANCODE_KP_MULTIPLY = (SDL_Scancode)K_KP_MULTIPLY,
SDL_SCANCODE_KP_MINUS = (SDL_Scancode)K_KP_MINUS,
SDL_SCANCODE_KP_PLUS = (SDL_Scancode)K_KP_PLUS,
SDL_SCANCODE_KP_ENTER = (SDL_Scancode)K_KP_ENTER,
SDL_SCANCODE_KP_1 = (SDL_Scancode)K_KP_END,
SDL_SCANCODE_KP_2 = (SDL_Scancode)K_KP_DOWNARROW,
SDL_SCANCODE_KP_3 = (SDL_Scancode)K_KP_PGDN,
SDL_SCANCODE_KP_4 = (SDL_Scancode)K_KP_LEFTARROW,
SDL_SCANCODE_KP_5 = (SDL_Scancode)K_KP_5,
SDL_SCANCODE_KP_6 = (SDL_Scancode)K_KP_RIGHTARROW,
SDL_SCANCODE_KP_7 = (SDL_Scancode)K_KP_HOME,
SDL_SCANCODE_KP_8 = (SDL_Scancode)K_KP_UPARROW,
SDL_SCANCODE_KP_9 = (SDL_Scancode)K_KP_PGUP,
SDL_SCANCODE_KP_0 = (SDL_Scancode)K_KP_INS,
SDL_SCANCODE_KP_PERIOD = (SDL_Scancode)K_KP_DEL,
SDL_SCANCODE_NONUSBACKSLASH = (SDL_Scancode)K_102ND,
SDL_SCANCODE_APPLICATION = (SDL_Scancode)K_MENU
