/********************************************************************
*
*
*	ClientGame: (Entity/Player State) -Events:
*
*
********************************************************************/
#pragma once

#include "shared/shared.h"
#include "shared/player_state.h"



/**
*
*
*
*	Core Entity Event Funcs:
*
*
*
**/
/**
*	Macro for debugging purposes:
**/
#define	DEBUG_PRINT_EVENT_NAME( eventNameStr ) \
	if( cl_debug_entity_events->integer ) \
	{ \
		clgi.Print( PRINT_DEVELOPER, "DEBUG EVENT: %s\n", eventNameStr ); \
	} \

/**
*   @brief  Checks for entity generated events and processes them for execution.
*           Entity events can be generated by either the entity type itself, or by riding with another entity.
*
*   @note   This only processes entity events, not player state events. Player state events are handled separately.
*           Called once per entity per frame to check for any new events to process.
*
*           Entity events are only processed once per event change, so if the event value hasn't changed since last frame, it won't be processed again.
*
*           It will pass along the client info for player type entities based on the skinnum decoding.
*
*   @param  cent        The client entity to check for events on.
**/
void CLG_Events_CheckForEntity( centity_t *cent );

/**
*   @brief  Checks for player state generated events(usually by PMove) and processed them for execution.
*   @note   This only processes player state events, not entity events. Entity events are handled separately.
*           Called once per frame for the local player to check for any new events to process.
*   @param  ops                 The old player state.
*   @param  ps                  The current player state.
*   @param  playerStateEvent    The player state event to process.
*   @param  lerpOrigin          The origin to process the event at.
*   @return True if an event was processed, false otherwise.
**/
const bool CLG_Events_CheckForLocalPlayerState( const player_state_t *ops, const player_state_t *ps, const int32_t playerStateEvent, const int32_t playerStateEventParm0, const Vector3 &lerpOrigin );



/**
*
*
*
*	General Events:
*
*
*
**/
/**
*   @brief  The local (PLAYER) footstep sound event handler.
**/
void CLG_LocalFootStepEvent( const int32_t entityNumber, const Vector3 & lerpOrigin );
/**
*   @brief  The generic (PLAYER) footstep sound event handler.
**/
void CLG_PlayerFootStepEvent( const int32_t entityNumber, const Vector3 &lerpOrigin );
/**
*   @brief  The generic (OTHER entity) footstep sound event handler.
**/
void CLG_OtherFootStepEvent( const int32_t entityNumber, const Vector3 &lerpOrigin );
/**
*   @brief  The generic footstep sound event handler.
**/
//void CLG_FootStepEvent( const int32_t entityNumber, const Vector3 &lerpOrigin );
/**
*   @brief  Passes on to CLG_FX_FootStepSound with isLadder beign true. Used by EV_FOOTSTEP_LADDER.
**/
void CLG_FootStepLadderEvent( const int32_t entityNumber, const Vector3 &lerpOrigin );